// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyskuyyocbleyfaicfpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5c2t1eXlvY2JsZXlmYWljZnBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2Mzk5NjgsImV4cCI6MjA3MjIxNTk2OH0.wgKLevlrllM3C_ZeqnpCZ_0Z5rQEaYoFijqmw-clejE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});